Removing commercial installations from merged dataset and moving function due to circular import
nestauk/asf_core_data pull request #84
Opened 2023-06-13 09:50 UTC by sofiapinto

# Description 

This PR fixes issues ...

closes #78 
closes #83 

# Instructions for Reviewer(s)

## Review

---

2023-06-13 14:51 UTC, sqr00t requested changes
Things to consider:
- Other variations of "Commercial" within installation_type?
- Use an explicit import in merge_proc_datasets.py for get_postcode_coordinates(), instead of importing everything from feature_engineering and moving a feature engineering function into data_cleaning.

2023-06-13 14:51 UTC, sqr00t commented on asf_core_data/pipeline/data_joining/merge_proc_datasets.py
> +    mcs_df = mcs_df[mcs_df["installation_type"] != "Commercial"]
This is fine, though I wonder if random spaces or other variations of "Commercial" string would come up.
Could use the following suggestion:

mcs_df = mcs_df[mcs_df["installation_type"].str.contains("Commercial")]

2023-06-13 14:51 UTC, sqr00t commented on asf_core_data/pipeline/preprocessing/data_cleaning.py
Shouldn't enhance_construction_age_band() be part of the feature_engineering:get_additional_features()?

Moving this enhancing function this way seems like a bandaid fix for getting merge_proc_datasets to work. Could instead try an explicit import of the only function from feature_engineering (feature_engineering.get_postcode_coordinates()) that is used in merge_proc_datasets?

i.e. from asf_core_data.pipeline.preprocessing.feature_engineering import get_postcode_coordinates

2023-06-13 15:24 UTC, sofiapinto commented on asf_core_data/pipeline/data_joining/merge_proc_datasets.py
> +    mcs_df = mcs_df[mcs_df["installation_type"] != "Commercial"]
It's not a problem so far, but I'll change it to: mcs_df = mcs_df[mcs_df["installation_type"].str.contains("commercial", case=False)] this way, it's not case sensitive

2023-06-15 14:19 UTC, sofiapinto commented on asf_core_data/pipeline/preprocessing/data_cleaning.py
hey @sqr00t - Even with importing the specific functions instead of the whole script, the problem still persists. I've looked further at the functions in `data_cleaning.py` and `feature_engineering.py` and I think the `enhance_construction_age_band()` function might actually might fit `data_cleaning.py` better than `feature_engineering.py`: the work in `enhance_construction_age_band()` is similar to the work in the `standardise_features()` function. Unless you really disagree with this and we find another way for this to work without causing the circular imports problem, I might just leave it at that. We can also always create a new issue later to improve on this, as I'm sure it can be improved.

2023-06-15 16:06 UTC, merged